# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'easyLIGO.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 857)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(480, 210, 441, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_OperationRecord = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_OperationRecord.setObjectName("lb_OperationRecord")
        self.verticalLayout.addWidget(self.lb_OperationRecord)
        self.tx_OperationRecord = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.tx_OperationRecord.setObjectName("tx_OperationRecord")
        self.verticalLayout.addWidget(self.tx_OperationRecord)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 210, 251, 129))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pb_OpenConfigFile = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pb_OpenConfigFile.setStyleSheet("font: 75 12pt \"Calibri\";\n"
"font: 75 12pt \"Calibri\";\n"
"rgb:(85, 170, 255);")
        self.pb_OpenConfigFile.setObjectName("pb_OpenConfigFile")
        self.verticalLayout_2.addWidget(self.pb_OpenConfigFile)
        self.tx_OpenFile = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.tx_OpenFile.setStyleSheet("font: 12pt \"Arial\";")
        self.tx_OpenFile.setObjectName("tx_OpenFile")
        self.verticalLayout_2.addWidget(self.tx_OpenFile)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(120, 370, 251, 71))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lb_OutFileName = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lb_OutFileName.setObjectName("lb_OutFileName")
        self.verticalLayout_3.addWidget(self.lb_OutFileName)
        self.le_OutFileName = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.le_OutFileName.setStyleSheet("font: 16pt \"Arial\";")
        self.le_OutFileName.setObjectName("le_OutFileName")
        self.verticalLayout_3.addWidget(self.le_OutFileName)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 26))
        self.menubar.setObjectName("menubar")
        self.menuHello_Easy_Ligo_Platform = QtWidgets.QMenu(self.menubar)
        self.menuHello_Easy_Ligo_Platform.setObjectName("menuHello_Easy_Ligo_Platform")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuHello_Easy_Ligo_Platform.addSeparator()
        self.menuHello_Easy_Ligo_Platform.addSeparator()
        self.menubar.addAction(self.menuHello_Easy_Ligo_Platform.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_OperationRecord.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#ffaa00;\">Operation Record</span></p></body></html>"))
        self.pb_OpenConfigFile.setText(_translate("MainWindow", "Open Config File"))
        self.lb_OutFileName.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#00ff00;\">OutFileName</span></p></body></html>"))
        self.menuHello_Easy_Ligo_Platform.setTitle(_translate("MainWindow", "Hello Easy Ligo Platform"))
